import 'resep.dart';

final List<Recipe> dummyResep = [
  Recipe(
    id: 1,
    title: "Nasi Goreng Spesial",
    description:
        "Nasi goreng khas Indonesia dengan cita rasa gurih, dilengkapi telur, ayam suwir, dan sayuran segar. Cocok untuk sarapan maupun makan malam.",
    imageUrl: "images/nasgor2.jpg",
    ingredients: [
      "2 piring nasi putih (sebaiknya nasi dingin)",
      "2 butir telur ayam",
      "100 gram ayam dada, rebus lalu suwir",
      "3 siung bawang merah, iris halus",
      "2 siung bawang putih, cincang",
      "2 sdm kecap manis",
      "1 sdm kecap asin",
      "1/2 sdt merica bubuk",
      "1/2 sdt garam",
      "1/2 sdt kaldu bubuk",
      "1 batang daun bawang, iris",
      "1 sdm minyak goreng",
      "Acar & kerupuk (pelengkap)",
    ],
    steps: [
      "Panaskan minyak goreng di wajan dengan api sedang.",
      "Tumis bawang merah dan bawang putih hingga harum dan sedikit kecoklatan.",
      "Masukkan telur, orak-arik hingga setengah matang.",
      "Masukkan ayam suwir, aduk hingga tercampur rata.",
      "Masukkan nasi putih, aduk dan tekan agar nasi terurai.",
      "Tambahkan kecap manis, kecap asin, garam, merica, dan kaldu bubuk.",
      "Aduk rata hingga nasi berubah warna dan bumbu meresap.",
      "Masukkan daun bawang, aduk sebentar lalu koreksi rasa.",
      "Angkat dan sajikan nasi goreng selagi hangat.",
      "Sajikan dengan acar, kerupuk, dan telur mata sapi jika suka.",
    ],
  ),

  Recipe(
    id: 2,
    title: "Mie Goreng",
    description:
        "Mie goreng sederhana dengan cita rasa gurih dan lezat, dipadukan dengan sayuran segar dan bumbu khas rumahan. Cocok untuk menu cepat dan praktis.",
    imageUrl: "images/migor.jpg",
    ingredients: [
      "1 bungkus mie telur atau mie instan tanpa bumbu",
      "1 butir telur ayam",
      "2 siung bawang putih, cincang halus",
      "1/2 buah bawang bombay, iris tipis",
      "1 batang daun bawang, iris",
      "1 genggam sawi hijau atau kol, iris",
      "2 sdm kecap manis",
      "1 sdm kecap asin",
      "1/2 sdt merica bubuk",
      "1/2 sdt garam",
      "1/2 sdt kaldu bubuk (opsional)",
      "1 sdm minyak goreng",
      "Acar dan kerupuk (pelengkap)",
    ],
    steps: [
      "Rebus mie hingga setengah matang, tiriskan dan sisihkan.",
      "Panaskan minyak goreng di wajan dengan api sedang.",
      "Tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan telur, orak-arik hingga matang.",
      "Masukkan sayuran, tumis sebentar hingga layu.",
      "Masukkan mie rebus ke dalam wajan, aduk rata.",
      "Tambahkan kecap manis, kecap asin, garam, merica, dan kaldu bubuk.",
      "Aduk terus hingga bumbu merata dan mie matang sempurna.",
      "Masukkan daun bawang, aduk sebentar lalu angkat.",
      "Sajikan mie goreng selagi hangat dengan acar dan kerupuk.",
    ],
  ),

  Recipe(
    id: 3,
    title: "Ayam Geprek",
    description:
        "Ayam goreng crispy yang digeprek bersama sambal bawang pedas, menghasilkan perpaduan rasa gurih, renyah, dan pedas yang menggugah selera. Cocok untuk pencinta makanan pedas.",
    imageUrl: "images/ayprek.jpg",
    ingredients: [
      "2 potong ayam goreng crispy",
      "10 buah cabai rawit merah (sesuai selera)",
      "4 siung bawang putih",
      "1/2 sdt garam",
      "1/4 sdt gula pasir",
      "1/4 sdt kaldu bubuk (opsional)",
      "3 sdm minyak goreng panas",
      "Nasi putih hangat (pelengkap)",
      "Lalapan segar (opsional)",
    ],
    steps: [
      "Goreng ayam crispy hingga matang dan berwarna keemasan, lalu tiriskan.",
      "Siapkan cobek, masukkan cabai rawit, bawang putih, garam, gula, dan kaldu bubuk.",
      "Ulek bahan sambal hingga halus atau sesuai tekstur yang diinginkan.",
      "Siram sambal dengan minyak goreng panas agar aroma lebih harum.",
      "Letakkan ayam goreng di atas sambal, lalu geprek hingga ayam sedikit hancur dan sambal meresap.",
      "Sajikan ayam geprek selagi hangat bersama nasi putih dan lalapan.",
    ],
  ),

  Recipe(
    id: 4,
    title: "Nasi Goreng Kampung",
    description:
        "Nasi goreng tradisional khas rumahan dengan aroma terasi yang kuat, rasa pedas cabai rawit, dan bumbu sederhana. Cita rasa autentik yang mengingatkan pada masakan kampung.",
    imageUrl: "images/nasgorkampung.jpg",
    ingredients: [
      "2 piring nasi putih dingin",
      "3 siung bawang merah, iris tipis",
      "2 siung bawang putih, cincang halus",
      "5 buah cabai rawit merah, iris (sesuai selera)",
      "1 sdt terasi bakar",
      "2 sdm kecap manis",
      "1/2 sdt garam",
      "1/4 sdt kaldu bubuk (opsional)",
      "1/4 sdt merica bubuk",
      "2 sdm minyak goreng",
      "Telur ceplok (pelengkap)",
      "Timun dan kerupuk (pelengkap)",
    ],
    steps: [
      "Panaskan minyak goreng di wajan dengan api sedang.",
      "Tumis bawang merah, bawang putih, dan cabai rawit hingga harum dan sedikit layu.",
      "Masukkan terasi bakar, aduk hingga terasi larut dan aromanya keluar.",
      "Masukkan nasi putih, aduk dan tekan agar nasi terurai.",
      "Tambahkan kecap manis, garam, merica, dan kaldu bubuk.",
      "Aduk terus hingga nasi tercampur rata, kering, dan harum.",
      "Koreksi rasa, lalu masak sebentar hingga nasi goreng matang sempurna.",
      "Angkat dan sajikan nasi goreng kampung selagi hangat.",
      "Sajikan bersama telur ceplok, timun, dan kerupuk.",
    ],
  ),

  Recipe(
    id: 5,
    title: "Soto Ayam Lamongan",
    description:
        "Soto ayam khas Lamongan dengan kuah kuning gurih dan taburan koya yang khas. Perpaduan kaldu ayam yang kaya rempah menjadikan hidangan ini hangat dan menggugah selera.",
    imageUrl: "images/sotolamonganayam.webp",
    ingredients: [
      "1 ekor ayam, potong menjadi beberapa bagian",
      "2 liter air",
      "6 siung bawang merah",
      "4 siung bawang putih",
      "3 cm kunyit, bakar",
      "2 cm jahe",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "2 cm lengkuas, memarkan",
      "1 sdt ketumbar bubuk",
      "1 sdt garam",
      "1/2 sdt gula pasir",
      "1/2 sdt merica bubuk",
      "2 sdm minyak goreng",
      "100 gram soun, rendam air panas",
      "2 butir telur rebus, belah dua",
      "Koya soto secukupnya",
      "Daun bawang & seledri, iris halus",
      "Jeruk nipis dan sambal (pelengkap)",
    ],
    steps: [
      "Rebus ayam dalam air hingga matang dan empuk, angkat ayam lalu saring kaldu.",
      "Suwir daging ayam, sisihkan.",
      "Haluskan bawang merah, bawang putih, kunyit, jahe, dan ketumbar.",
      "Panaskan minyak, tumis bumbu halus hingga harum dan matang.",
      "Masukkan serai, daun jeruk, dan lengkuas, aduk hingga wangi.",
      "Masukkan bumbu tumis ke dalam kaldu ayam, masak hingga mendidih.",
      "Tambahkan garam, gula, dan merica, aduk rata dan koreksi rasa.",
      "Siapkan mangkuk, isi dengan soun, suwiran ayam, dan telur rebus.",
      "Siram dengan kuah soto panas.",
      "Taburi koya, daun bawang, dan seledri.",
      "Sajikan soto ayam Lamongan selagi hangat dengan jeruk nipis dan sambal.",
    ],
  ),

  Recipe(
    id: 6,
    title: "Rendang Padang",
    description:
        "Rendang Padang adalah masakan khas Minangkabau berbahan dasar daging sapi yang dimasak perlahan dengan santan dan rempah-rempah hingga kering dan berwarna cokelat kehitaman. Rasanya gurih, pedas, dan kaya rempah.",
    imageUrl: "images/rendangpadang.jpg",
    ingredients: [
      "1 kg daging sapi bagian paha atau sandung lamur, potong kotak",
      "1 liter santan kental dari 2 butir kelapa",
      "500 ml santan encer",
      "10 buah cabai merah keriting",
      "5 buah cabai rawit merah (opsional)",
      "8 siung bawang merah",
      "5 siung bawang putih",
      "3 cm jahe",
      "3 cm lengkuas",
      "2 batang serai, memarkan",
      "2 lembar daun kunyit, iris halus",
      "4 lembar daun jeruk",
      "1 sdt ketumbar bubuk",
      "1/2 sdt jintan bubuk",
      "2 sdt garam",
      "1 sdt gula aren",
    ],
    steps: [
      "Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, jahe, lengkuas, ketumbar, dan jintan.",
      "Masukkan bumbu halus ke dalam wajan besar, masak hingga harum dan berminyak.",
      "Masukkan serai, daun jeruk, dan daun kunyit, aduk hingga bumbu matang sempurna.",
      "Masukkan potongan daging sapi, aduk hingga daging terbalut bumbu.",
      "Tuangkan santan encer, masak dengan api sedang hingga daging mulai empuk.",
      "Masukkan santan kental, aduk perlahan agar santan tidak pecah.",
      "Masak rendang dengan api kecil sambil terus diaduk sesekali.",
      "Masak hingga kuah menyusut, mengering, dan bumbu melekat pada daging.",
      "Proses memasak membutuhkan waktu ±3–4 jam hingga rendang berwarna cokelat gelap.",
      "Angkat dan sajikan rendang Padang selagi hangat bersama nasi putih.",
    ],
  ),

  Recipe(
    id: 7,
    title: "Ayam Penyet",
    description:
        "Ayam goreng yang digeprek bersama sambal pedas khas Indonesia, disajikan dengan lalapan segar. Perpaduan ayam gurih dan sambal pedas menjadikan hidangan ini favorit banyak orang.",
    imageUrl: "images/ayampenyet.jpeg",
    ingredients: [
      "2 potong ayam goreng",
      "8 buah cabai rawit merah",
      "2 buah cabai merah besar",
      "2 siung bawang putih",
      "1 buah tomat merah",
      "1/2 sdt garam",
      "1/4 sdt gula pasir",
      "2 sdm minyak goreng panas",
      "Timun, kemangi, dan kol (lalapan)",
      "Nasi putih hangat (pelengkap)",
    ],
    steps: [
      "Goreng ayam hingga matang dan berwarna keemasan, tiriskan.",
      "Siapkan cobek, masukkan cabai rawit, cabai merah, bawang putih, tomat, garam, dan gula.",
      "Ulek semua bahan sambal hingga halus atau sesuai tekstur yang diinginkan.",
      "Siram sambal dengan minyak goreng panas agar aroma sambal lebih harum.",
      "Letakkan ayam goreng di atas sambal, lalu penyet hingga sedikit hancur.",
      "Sajikan ayam penyet selagi hangat bersama nasi putih dan lalapan segar.",
    ],
  ),

  Recipe(
    id: 8,
    title: "Bakso Malang",
    description:
        "Bakso Malang khas Jawa Timur yang disajikan lengkap dengan bakso sapi kenyal, bakso goreng, tahu, pangsit goreng, dan mie kuning dalam kuah kaldu gurih yang hangat.",
    imageUrl: "images/baksomalangg.webp",
    ingredients: [
      "500 gram daging sapi giling",
      "100 gram tepung tapioka",
      "4 siung bawang putih, haluskan",
      "1 butir putih telur",
      "1 sdt garam",
      "1/2 sdt merica bubuk",
      "1/2 sdt kaldu bubuk",
      "1/2 sdt baking powder (opsional)",
      "2 liter air",
      "2 batang daun bawang",
      "1 batang seledri",
      "2 sdm bawang goreng",
      "Mie kuning secukupnya",
      "Tahu putih goreng",
      "Pangsit goreng",
      "Bakso goreng (opsional)",
    ],
    steps: [
      "Campurkan daging sapi giling, bawang putih halus, putih telur, garam, merica, kaldu bubuk, dan baking powder.",
      "Tambahkan tepung tapioka, aduk hingga adonan kalis dan bisa dibentuk.",
      "Didihkan air dalam panci, kecilkan api.",
      "Bentuk adonan bakso menjadi bulatan, masukkan ke air panas.",
      "Rebus hingga bakso mengapung dan matang, angkat dan tiriskan.",
      "Untuk kuah, gunakan air rebusan bakso, tambahkan daun bawang, seledri, dan bumbu secukupnya.",
      "Siapkan mangkuk, masukkan mie kuning, tahu, pangsit goreng, dan bakso.",
      "Siram dengan kuah kaldu panas.",
      "Taburi bawang goreng dan seledri.",
      "Sajikan bakso Malang selagi hangat.",
    ],
  ),

  Recipe(
    id: 9,
    title: "Gado-Gado",
    description:
        "Gado-gado adalah salad khas Indonesia yang terdiri dari aneka sayuran rebus, tahu, tempe, dan telur, disiram dengan bumbu kacang yang gurih dan sedikit manis.",
    imageUrl: "images/gadogado.png",
    ingredients: [
      "100 gram tauge, siangi",
      "100 gram kol, iris kasar",
      "2 buah kentang, rebus dan potong",
      "2 butir telur rebus, belah dua",
      "1 papan tempe, goreng dan potong",
      "2 buah tahu putih, goreng dan potong",
      "Daun selada (opsional)",
      "Kerupuk dan emping (pelengkap)",

      // Bumbu kacang
      "200 gram kacang tanah goreng",
      "3 siung bawang putih",
      "3 buah cabai rawit merah",
      "1 sdm gula merah",
      "1/2 sdt garam",
      "1 sdt air asam jawa",
      "200 ml air panas",
    ],
    steps: [
      "Rebus tauge dan kol sebentar hingga layu, tiriskan.",
      "Rebus kentang hingga empuk, potong-potong.",
      "Haluskan kacang tanah, bawang putih, cabai rawit, gula merah, dan garam.",
      "Tambahkan air asam jawa dan air panas, aduk hingga bumbu kacang kental.",
      "Tata sayuran rebus, tahu, tempe, dan telur di atas piring.",
      "Siram dengan bumbu kacang secukupnya.",
      "Sajikan gado-gado dengan kerupuk atau emping.",
    ],
  ),

  Recipe(
    id: 10,
    title: "Rawon Surabaya",
    description:
        "Rawon Surabaya adalah sup daging sapi dengan kuah hitam khas dari kluwek. Rasanya gurih, kaya rempah, dan biasanya disajikan dengan tauge pendek serta sambal.",
    imageUrl: "images/rawonsurabaya.jpg",
    ingredients: [
      "500 gram daging sapi, potong dadu",
      "2 liter air",
      "5 buah kluwek, ambil isinya",
      "6 siung bawang merah",
      "4 siung bawang putih",
      "2 cm kunyit",
      "2 cm jahe",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "2 lembar daun salam",
      "1 sdt ketumbar bubuk",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",

      // Pelengkap
      "Tauge pendek",
      "Telur asin",
      "Bawang goreng",
      "Sambal terasi",
      "Kerupuk udang",
    ],
    steps: [
      "Rebus daging sapi hingga empuk, angkat dan potong-potong.",
      "Haluskan kluwek, bawang merah, bawang putih, kunyit, jahe, dan ketumbar.",
      "Tumis bumbu halus hingga harum dan matang.",
      "Masukkan serai, daun jeruk, dan daun salam, aduk rata.",
      "Masukkan bumbu tumis ke dalam air rebusan daging.",
      "Masukkan kembali daging sapi, masak hingga kuah menghitam dan bumbu meresap.",
      "Tambahkan garam dan gula, koreksi rasa.",
      "Sajikan rawon panas dengan tauge pendek, telur asin, bawang goreng, dan sambal.",
    ],
  ),

  Recipe(
    id: 11,
    title: "Pecel Madiun",
    description:
        "Pecel Madiun adalah hidangan khas Jawa Timur berupa aneka sayuran rebus yang disiram sambal kacang pedas manis, biasanya disajikan dengan peyek renyah.",
    imageUrl: "images/pecelmadiun.jpg",
    ingredients: [
      "100 gram tauge",
      "100 gram kol, iris kasar",
      "100 gram kacang panjang, potong",
      "100 gram daun singkong",
      "Daun kemangi (opsional)",
      "Peyek kacang (pelengkap)",

      // Sambal pecel
      "200 gram kacang tanah goreng",
      "3 siung bawang putih",
      "5 buah cabai rawit",
      "1 sdm gula merah",
      "1/2 sdt garam",
      "1 lembar daun jeruk",
      "Air panas secukupnya",
    ],
    steps: [
      "Rebus tauge, kol, kacang panjang, dan daun singkong secara terpisah hingga matang, tiriskan.",
      "Haluskan kacang tanah, bawang putih, cabai rawit, gula merah, garam, dan daun jeruk.",
      "Tambahkan air panas sedikit demi sedikit hingga sambal kental.",
      "Tata semua sayuran di atas piring.",
      "Siram dengan sambal pecel secukupnya.",
      "Sajikan dengan peyek kacang.",
    ],
  ),

  Recipe(
    id: 12,
    title: "Sop Buntut",
    description:
        "Sop buntut adalah sup khas Indonesia berbahan buntut sapi yang dimasak hingga empuk dengan kuah bening gurih dan sayuran segar.",
    imageUrl: "images/sopbuntut.jpg",
    ingredients: [
      "1 kg buntut sapi",
      "2 liter air",
      "3 buah wortel, potong",
      "3 buah kentang, potong",
      "1 batang daun bawang, iris",
      "1 batang seledri, iris",
      "4 siung bawang putih, geprek",
      "1/2 sdt pala bubuk",
      "1 sdt merica bubuk",
      "1 sdt garam",
      "1 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Rebus buntut sapi hingga empuk, buang air rebusan pertama.",
      "Rebus kembali buntut dengan air baru hingga empuk dan kaldunya keluar.",
      "Tumis bawang putih hingga harum, masukkan ke dalam kuah.",
      "Masukkan wortel dan kentang, masak hingga empuk.",
      "Bumbui dengan garam, gula, pala, dan merica.",
      "Masukkan daun bawang dan seledri, aduk sebentar lalu angkat.",
      "Sajikan sop buntut selagi hangat.",
    ],
  ),

  Recipe(
    id: 13,
    title: "Ayam Betutu",
    description:
        "Ayam Betutu adalah masakan khas Bali berupa ayam utuh berbumbu base genep yang dimasak perlahan hingga empuk dan kaya rempah.",
    imageUrl: "images/ayambetutu.jpg",
    ingredients: [
      "1 ekor ayam utuh",
      "8 siung bawang merah",
      "5 siung bawang putih",
      "8 buah cabai rawit",
      "3 cm jahe",
      "3 cm lengkuas",
      "2 batang serai",
      "3 lembar daun jeruk",
      "1 sdt ketumbar bubuk",
      "1 sdt garam",
      "1 sdt gula",
      "Daun pisang untuk membungkus",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, cabai, jahe, lengkuas, dan ketumbar.",
      "Tumis bumbu halus hingga harum, masukkan serai dan daun jeruk.",
      "Lumuri ayam dengan bumbu hingga merata.",
      "Bungkus ayam dengan daun pisang.",
      "Masak ayam dengan cara dikukus atau dipanggang hingga empuk.",
      "Angkat dan sajikan ayam betutu selagi hangat.",
    ],
  ),

  Recipe(
    id: 14,
    title: "Pempek Palembang",
    description:
        "Pempek Palembang adalah makanan khas Sumatera Selatan berbahan ikan tenggiri dan sagu, disajikan dengan kuah cuko asam manis pedas.",
    imageUrl: "images/pempek.webp",
    ingredients: [
      "500 gram ikan tenggiri giling",
      "300 gram tepung sagu",
      "250 ml air",
      "1 sdt garam",
      "1 butir telur",

      // Cuko
      "200 gram gula merah",
      "3 siung bawang putih",
      "5 buah cabai rawit",
      "1 sdt asam jawa",
      "500 ml air",
    ],
    steps: [
      "Campur ikan giling, air, garam, dan telur hingga rata.",
      "Tambahkan tepung sagu sedikit demi sedikit hingga adonan bisa dibentuk.",
      "Bentuk pempek sesuai selera.",
      "Rebus pempek hingga mengapung, angkat dan tiriskan.",
      "Goreng pempek sebelum disajikan.",
      "Rebus semua bahan cuko hingga mendidih dan rasa seimbang.",
      "Sajikan pempek dengan kuah cuko.",
    ],
  ),

  Recipe(
    id: 15,
    title: "Mie Aceh",
    description:
        "Mie Aceh adalah mie tebal khas Aceh dengan cita rasa pedas dan kaya rempah, dimasak bersama daging atau seafood.",
    imageUrl: "images/mieaceh.jpg",
    ingredients: [
      "200 gram mie kuning tebal",
      "150 gram daging sapi atau seafood",
      "4 siung bawang merah",
      "3 siung bawang putih",
      "5 buah cabai merah",
      "2 sdm bubuk kari",
      "1 sdt paprika bubuk",
      "1 sdt kecap manis",
      "1 sdt kecap asin",
      "1 batang daun bawang",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Rebus mie hingga setengah matang, tiriskan.",
      "Haluskan bawang merah, bawang putih, dan cabai.",
      "Tumis bumbu halus hingga harum, masukkan bubuk kari.",
      "Masukkan daging atau seafood, masak hingga matang.",
      "Masukkan mie, kecap manis, dan kecap asin.",
      "Aduk hingga bumbu meresap.",
      "Masukkan daun bawang, aduk sebentar lalu sajikan.",
    ],
  ),

  Recipe(
    id: 16,
    title: "Lontong Sayur",
    description:
        "Lontong sayur adalah hidangan khas Indonesia berupa potongan lontong yang disiram kuah santan labu siam gurih, biasanya disajikan dengan telur rebus dan sambal.",
    imageUrl: "images/lontongsayur.jpeg",
    ingredients: [
      "1 papan lontong, potong-potong",
      "1 buah labu siam, iris tipis",
      "500 ml santan encer",
      "250 ml santan kental",
      "5 siung bawang merah",
      "3 siung bawang putih",
      "2 butir kemiri",
      "2 cm lengkuas",
      "2 lembar daun salam",
      "1 sdt garam",
      "1/2 sdt gula",
      "2 butir telur rebus",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, dan kemiri.",
      "Tumis bumbu halus hingga harum.",
      "Masukkan lengkuas dan daun salam, aduk rata.",
      "Masukkan labu siam, aduk hingga layu.",
      "Tuangkan santan encer, masak hingga labu empuk.",
      "Tambahkan santan kental, garam, dan gula, aduk perlahan.",
      "Masak hingga kuah mengental dan gurih.",
      "Sajikan lontong dalam mangkuk, siram dengan kuah labu.",
      "Tambahkan telur rebus sebagai pelengkap.",
    ],
  ),

  Recipe(
    id: 17,
    title: "Kari Ayam",
    description:
        "Kari ayam adalah masakan berkuah santan kental dengan aroma rempah yang kuat dan rasa gurih pedas khas Nusantara.",
    imageUrl: "images/kariayam.jpg",
    ingredients: [
      "1 ekor ayam, potong-potong",
      "800 ml santan",
      "6 siung bawang merah",
      "4 siung bawang putih",
      "3 cm kunyit",
      "3 cm jahe",
      "2 sdm bubuk kari",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, kunyit, dan jahe.",
      "Tumis bumbu halus hingga harum dan matang.",
      "Masukkan bubuk kari, serai, dan daun jeruk, aduk rata.",
      "Masukkan potongan ayam, masak hingga ayam berubah warna.",
      "Tuangkan santan sedikit demi sedikit sambil diaduk.",
      "Masak dengan api kecil hingga ayam empuk dan kuah mengental.",
      "Tambahkan garam dan gula, koreksi rasa.",
      "Angkat dan sajikan kari ayam selagi hangat.",
    ],
  ),

  Recipe(
    id: 18,
    title: "Gulai Ikan",
    description:
        "Gulai ikan adalah masakan berkuah santan kuning dengan cita rasa gurih dan aroma rempah, menggunakan ikan segar sebagai bahan utama.",
    imageUrl: "images/gulaiikan.jpg",
    ingredients: [
      "500 gram ikan (tongkol/kakap)",
      "600 ml santan",
      "5 siung bawang merah",
      "3 siung bawang putih",
      "3 cm kunyit",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, dan kunyit.",
      "Tumis bumbu halus hingga harum.",
      "Masukkan serai dan daun jeruk, aduk hingga wangi.",
      "Tuangkan santan, masak dengan api kecil sambil diaduk.",
      "Masukkan potongan ikan.",
      "Masak hingga ikan matang dan bumbu meresap.",
      "Tambahkan garam dan gula, koreksi rasa.",
      "Sajikan gulai ikan selagi hangat.",
    ],
  ),

  Recipe(
    id: 19,
    title: "Opor Ayam",
    description:
        "Opor ayam adalah hidangan ayam berkuah santan gurih dengan aroma rempah lembut, sering disajikan saat hari raya.",
    imageUrl: "images/oporayam.webp",
    ingredients: [
      "1 ekor ayam, potong-potong",
      "800 ml santan",
      "6 siung bawang merah",
      "4 siung bawang putih",
      "2 butir kemiri",
      "2 batang serai",
      "3 cm lengkuas",
      "2 lembar daun salam",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, dan kemiri.",
      "Tumis bumbu halus hingga harum.",
      "Masukkan serai, lengkuas, dan daun salam.",
      "Masukkan ayam, masak hingga ayam berubah warna.",
      "Tuangkan santan sedikit demi sedikit sambil diaduk.",
      "Masak dengan api kecil hingga ayam empuk.",
      "Tambahkan garam dan gula, koreksi rasa.",
      "Angkat dan sajikan opor ayam selagi hangat.",
    ],
  ),

  Recipe(
    id: 20,
    title: "Pepes Ikan",
    description:
        "Pepes ikan adalah hidangan khas Indonesia berupa ikan berbumbu rempah yang dibungkus daun pisang lalu dikukus hingga harum.",
    imageUrl: "images/pepesikan.jpg",
    ingredients: [
      "500 gram ikan (nila/kembung)",
      "2 lembar daun pisang",
      "5 siung bawang merah",
      "3 siung bawang putih",
      "3 buah cabai merah",
      "2 cm kunyit",
      "2 batang serai",
      "3 lembar daun jeruk",
      "1 sdt garam",
      "1/2 sdt gula",
      "Daun kemangi (opsional)",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, cabai, dan kunyit.",
      "Lumuri ikan dengan bumbu halus hingga merata.",
      "Tambahkan serai, daun jeruk, dan kemangi.",
      "Bungkus ikan dengan daun pisang dan semat dengan lidi.",
      "Kukus pepes ikan hingga matang dan harum.",
      "Angkat dan sajikan pepes ikan selagi hangat.",
    ],
  ),

  Recipe(
    id: 21,
    title: "Sate Madura",
    description:
        "Sate Madura adalah sate ayam khas Jawa Timur dengan bumbu kacang gurih manis dan aroma kecap yang khas, disajikan dengan lontong atau nasi.",
    imageUrl: "images/satemadura.webp",
    ingredients: [
      "500 gram daging ayam fillet, potong dadu",
      "Tusuk sate secukupnya",
      "2 sdm kecap manis",
      "1 sdt air jeruk nipis",
      "1/2 sdt garam",

      // Bumbu kacang
      "200 gram kacang tanah goreng",
      "3 siung bawang putih",
      "3 buah cabai merah",
      "1 sdm gula merah",
      "1/2 sdt garam",
      "200 ml air",
    ],
    steps: [
      "Lumuri daging ayam dengan kecap manis, air jeruk nipis, dan garam, diamkan 15 menit.",
      "Tusuk daging ayam pada tusuk sate.",
      "Haluskan kacang tanah, bawang putih, cabai merah, gula merah, dan garam.",
      "Masak bumbu kacang dengan air hingga mengental.",
      "Bakar sate di atas bara api sambil dioles sisa bumbu hingga matang.",
      "Sajikan sate dengan siraman bumbu kacang dan kecap manis.",
    ],
  ),

  Recipe(
    id: 22,
    title: "Sate Padang",
    description:
        "Sate Padang adalah sate khas Sumatera Barat dengan kuah kental berwarna kuning pedas yang terbuat dari rempah-rempah.",
    imageUrl: "images/satepadang.webp",
    ingredients: [
      "500 gram daging sapi",
      "Tusuk sate secukupnya",

      // Kuah sate Padang
      "6 siung bawang merah",
      "4 siung bawang putih",
      "3 buah cabai merah",
      "2 cm kunyit",
      "2 cm jahe",
      "2 sdm tepung beras",
      "700 ml air rebusan daging",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Rebus daging sapi hingga empuk, potong dadu, dan tusuk pada tusuk sate.",
      "Haluskan bawang merah, bawang putih, cabai, kunyit, dan jahe.",
      "Tumis bumbu halus hingga harum.",
      "Tambahkan air rebusan daging, masak hingga mendidih.",
      "Larutkan tepung beras dengan sedikit air, masukkan ke kuah.",
      "Masak hingga kuah mengental, bumbui garam dan gula.",
      "Bakar sate sebentar.",
      "Sajikan sate dengan siraman kuah Padang panas.",
    ],
  ),

  Recipe(
    id: 23,
    title: "Sayur Asem",
    description:
        "Sayur asem adalah masakan berkuah bening dengan rasa asam segar, berisi aneka sayuran dan cocok disantap sebagai menu sehari-hari.",
    imageUrl: "images/sayurasam.jpg",
    ingredients: [
      "1 buah jagung manis, potong",
      "100 gram melinjo",
      "100 gram kacang panjang, potong",
      "1 buah labu siam, potong",
      "2 sdm air asam jawa",
      "2 lembar daun salam",
      "2 cm lengkuas",

      // Bumbu halus
      "4 siung bawang merah",
      "2 siung bawang putih",
      "2 buah cabai merah",
      "1 sdt garam",
      "1/2 sdt gula",
    ],
    steps: [
      "Didihkan air, masukkan jagung dan melinjo hingga setengah empuk.",
      "Masukkan labu siam dan kacang panjang.",
      "Masukkan bumbu halus, daun salam, dan lengkuas.",
      "Tambahkan air asam jawa, garam, dan gula.",
      "Masak hingga semua sayuran empuk dan kuah segar.",
      "Angkat dan sajikan sayur asem hangat.",
    ],
  ),

  Recipe(
    id: 24,
    title: "Capcay Jawa",
    description:
        "Capcay Jawa adalah tumisan sayuran sederhana dengan cita rasa gurih dan sedikit manis khas masakan rumahan Jawa.",
    imageUrl: "images/capcayjawa.jpeg",
    ingredients: [
      "1 buah wortel, iris",
      "100 gram kol, iris kasar",
      "5 butir bakso, iris",
      "3 siung bawang putih, cincang",
      "1 butir telur",
      "200 ml air",
      "1 sdt kecap manis",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Minyak untuk menumis",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih hingga harum.",
      "Masukkan telur, orak-arik hingga matang.",
      "Masukkan bakso dan wortel, tumis sebentar.",
      "Masukkan kol dan air.",
      "Tambahkan kecap manis, garam, dan merica.",
      "Masak hingga sayuran matang.",
      "Angkat dan sajikan capcay Jawa hangat.",
    ],
  ),

  Recipe(
    id: 25,
    title: "Tumis Kangkung",
    description:
        "Tumis kangkung adalah masakan sederhana berbahan kangkung segar yang ditumis dengan bawang putih dan cabai, bercita rasa gurih dan lezat.",
    imageUrl: "images/tumiskangkung.jpg",
    ingredients: [
      "1 ikat kangkung, siangi",
      "3 siung bawang putih, iris",
      "5 buah cabai rawit",
      "1 sdm saus tiram",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak goreng di wajan.",
      "Tumis bawang putih dan cabai hingga harum.",
      "Masukkan kangkung, aduk cepat.",
      "Tambahkan saus tiram, garam, dan gula.",
      "Masak hingga kangkung layu.",
      "Angkat dan sajikan tumis kangkung selagi hangat.",
    ],
  ),

  Recipe(
    id: 26,
    title: "Ikan Bakar Rica",
    description:
        "Ikan bakar khas Manado dengan bumbu rica-rica pedas dan segar, berpadu aroma bakaran yang menggugah selera.",
    imageUrl: "images/ikanbakarrica.webp",
    ingredients: [
      "1 ekor ikan (nila/kakap), belah dua",
      "2 sdm air jeruk nipis",
      "1 sdt garam",
      "5 buah cabai merah",
      "8 buah cabai rawit",
      "6 siung bawang merah",
      "3 siung bawang putih",
      "2 cm jahe",
      "1 batang serai",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Lumuri ikan dengan jeruk nipis dan garam, diamkan 10 menit.",
      "Haluskan cabai, bawang merah, bawang putih, dan jahe.",
      "Tumis bumbu halus bersama serai hingga harum.",
      "Lumuri ikan dengan bumbu rica.",
      "Bakar ikan sambil dioles sisa bumbu hingga matang.",
      "Sajikan ikan bakar rica selagi panas.",
    ],
  ),

  Recipe(
    id: 27,
    title: "Bebek Goreng",
    description:
        "Bebek goreng renyah di luar dan empuk di dalam, disajikan dengan sambal pedas.",
    imageUrl: "images/bebekgoreng.jpg",
    ingredients: [
      "1 ekor bebek, potong",
      "5 siung bawang putih",
      "3 siung bawang merah",
      "2 cm lengkuas",
      "2 lembar daun salam",
      "1 sdt garam",
      "Air secukupnya",
      "Minyak goreng",
    ],
    steps: [
      "Rebus bebek bersama bumbu hingga empuk dan air menyusut.",
      "Panaskan minyak, goreng bebek hingga kecokelatan.",
      "Angkat dan tiriskan.",
      "Sajikan dengan sambal favorit.",
    ],
  ),

  Recipe(
    id: 28,
    title: "Kwetiau Goreng",
    description:
        "Kwetiau goreng ala kaki lima dengan rasa gurih dan aroma smokey.",
    imageUrl: "images/kwetiaugoreng.jpg",
    ingredients: [
      "200 gram kwetiau",
      "1 butir telur",
      "3 siung bawang putih",
      "100 gram sawi",
      "2 sdm kecap asin",
      "1 sdt kecap manis",
      "Minyak goreng",
    ],
    steps: [
      "Tumis bawang putih hingga harum.",
      "Masukkan telur, orak-arik.",
      "Masukkan kwetiau dan sayuran.",
      "Tambahkan kecap asin dan kecap manis.",
      "Aduk hingga matang dan sajikan.",
    ],
  ),

  Recipe(
    id: 29,
    title: "Martabak Telur",
    description:
        "Martabak telur gurih dengan isian daging cincang dan daun bawang.",
    imageUrl: "images/martabaktelur.webp",
    ingredients: [
      "Kulit martabak",
      "200 gram daging cincang",
      "3 butir telur",
      "2 batang daun bawang",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Minyak goreng",
    ],
    steps: [
      "Campur daging, telur, daun bawang, garam, dan merica.",
      "Isi kulit martabak dengan adonan.",
      "Goreng hingga kecokelatan.",
      "Angkat dan sajikan hangat.",
    ],
  ),

  Recipe(
    id: 30,
    title: "Tahu Tek Surabaya",
    description:
        "Tahu tek khas Surabaya dengan bumbu petis manis gurih dan kacang.",
    imageUrl: "images/TahuTekSurabaya.webp",
    ingredients: [
      "5 buah tahu goreng",
      "100 gram tauge",
      "2 buah kentang rebus",
      "2 sdm petis udang",
      "100 gram kacang tanah goreng",
      "2 siung bawang putih",
      "Garam secukupnya",
    ],
    steps: [
      "Haluskan kacang tanah, bawang putih, dan petis.",
      "Potong tahu dan kentang.",
      "Tata semua bahan di piring.",
      "Siram bumbu petis dan aduk rata.",
    ],
  ),

  Recipe(
    id: 31,
    title: "Ketoprak",
    description:
        "Ketoprak Jakarta dengan ketupat, tahu, bihun, dan bumbu kacang.",
    imageUrl: "images/ketoprak.jpg",
    ingredients: [
      "Ketupat",
      "Tahu goreng",
      "Bihun rebus",
      "100 gram kacang tanah goreng",
      "2 siung bawang putih",
      "Kecap manis",
      "Garam",
    ],
    steps: [
      "Haluskan kacang dan bawang putih.",
      "Tambahkan kecap dan garam.",
      "Susun ketupat, tahu, dan bihun.",
      "Siram bumbu kacang dan sajikan.",
    ],
  ),

  Recipe(
    id: 32,
    title: "Soto Betawi",
    description: "Soto Betawi dengan kuah santan creamy dan daging sapi empuk.",
    imageUrl: "images/sotobetawi.png",
    ingredients: [
      "500 gram daging sapi",
      "800 ml santan",
      "3 siung bawang putih",
      "2 cm jahe",
      "2 batang serai",
      "Garam dan merica",
    ],
    steps: [
      "Rebus daging hingga empuk.",
      "Tumis bawang putih dan jahe.",
      "Masukkan ke kuah bersama santan.",
      "Sajikan dengan emping dan tomat.",
    ],
  ),

  Recipe(
    id: 33,
    title: "Ayam Goreng Lengkuas",
    description: "Ayam goreng gurih dengan taburan serundeng lengkuas renyah.",
    imageUrl: "images/ayamgorenglengkuas.jpeg",
    ingredients: [
      "1 ekor ayam, potong",
      "200 gram lengkuas parut",
      "4 siung bawang putih",
      "2 lembar daun salam",
      "Garam",
      "Minyak goreng",
    ],
    steps: [
      "Ungkep ayam dengan bumbu hingga empuk.",
      "Goreng ayam hingga kecokelatan.",
      "Goreng lengkuas hingga kering.",
      "Taburi ayam dengan lengkuas goreng.",
    ],
  ),

  Recipe(
    id: 34,
    title: "Sambal Matah",
    description: "Sambal matah khas Bali dengan rasa segar dan pedas.",
    imageUrl: "images/sambalmatah.jpeg",
    ingredients: [
      "6 siung bawang merah",
      "8 cabai rawit",
      "2 batang serai",
      "1 buah jeruk limau",
      "4 sdm minyak kelapa panas",
      "Garam",
    ],
    steps: [
      "Iris halus semua bahan.",
      "Tambahkan perasan jeruk limau.",
      "Siram minyak panas.",
      "Aduk rata dan sajikan.",
    ],
  ),

  Recipe(
    id: 35,
    title: "Mie Bakso",
    description: "Mie bakso dengan kuah kaldu sapi gurih dan bakso kenyal.",
    imageUrl: "images/miebakso.jpg",
    ingredients: [
      "Mie telur",
      "Bakso sapi",
      "Kaldu sapi",
      "Sawi hijau",
      "Bawang goreng",
    ],
    steps: [
      "Rebus mie dan sawi.",
      "Panaskan kaldu dan bakso.",
      "Susun mie dalam mangkuk.",
      "Tuang kuah dan sajikan dengan bawang goreng.",
    ],
  ),

  Recipe(
    id: 36,
    title: "Nasi Uduk",
    description:
        "Nasi uduk adalah nasi gurih khas Betawi yang dimasak dengan santan dan rempah, memiliki aroma harum dan rasa lezat.",
    imageUrl: "images/nasiuduk.jpg",
    ingredients: [
      "2 cup beras, cuci bersih",
      "400 ml santan",
      "2 batang serai, memarkan",
      "3 lembar daun salam",
      "2 lembar daun jeruk",
      "1 sdt garam",
      "Air secukupnya",
      "Bawang goreng (pelengkap)",
      "Telur dadar iris (pelengkap)",
      "Sambal dan tempe orek (pelengkap)",
    ],
    steps: [
      "Cuci beras hingga bersih lalu tiriskan.",
      "Masukkan beras ke dalam panci atau rice cooker.",
      "Tambahkan santan, air, garam, serai, daun salam, dan daun jeruk.",
      "Aduk rata lalu masak hingga nasi matang dan harum.",
      "Aduk nasi uduk dan diamkan sebentar.",
      "Sajikan nasi uduk hangat dengan pelengkap.",
    ],
  ),

  Recipe(
    id: 37,
    title: "Bubur Ayam",
    description:
        "Bubur ayam adalah hidangan sarapan populer berupa bubur nasi lembut yang disajikan dengan ayam suwir, kacang kedelai, dan kuah gurih.",
    imageUrl: "images/buburayam.jpeg",
    ingredients: [
      "1 cup beras",
      "1 liter air",
      "200 gram ayam, rebus dan suwir",
      "500 ml kaldu ayam",
      "2 siung bawang putih",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Kacang kedelai goreng",
      "Daun bawang, seledri",
      "Bawang goreng",
      "Kecap asin dan sambal (pelengkap)",
    ],
    steps: [
      "Cuci beras lalu masak dengan air hingga menjadi bubur lembut.",
      "Haluskan bawang putih lalu tumis hingga harum.",
      "Masukkan tumisan bawang ke dalam bubur.",
      "Tambahkan kaldu ayam, garam, dan merica.",
      "Masak hingga bubur kental dan matang.",
      "Sajikan bubur dengan ayam suwir dan topping lainnya.",
    ],
  ),

  Recipe(
    id: 38,
    title: "Nasi Kuning",
    description:
        "Nasi kuning adalah nasi berwarna kuning cerah dari kunyit, dimasak dengan santan dan rempah, biasanya disajikan saat acara syukuran.",
    imageUrl: "images/nasikuning.jpg",
    ingredients: [
      "2 cup beras",
      "400 ml santan",
      "2 cm kunyit, haluskan",
      "2 batang serai, memarkan",
      "3 lembar daun salam",
      "1 sdt garam",
      "Air secukupnya",
      "Ayam goreng dan telur (pelengkap)",
    ],
    steps: [
      "Cuci beras hingga bersih.",
      "Campur santan dengan kunyit halus, aduk rata.",
      "Masukkan beras, serai, daun salam, dan garam.",
      "Masak hingga nasi matang dan berwarna kuning.",
      "Aduk nasi kuning dan sajikan dengan lauk.",
    ],
  ),

  Recipe(
    id: 39,
    title: "Ayam Kecap",
    description:
        "Ayam kecap adalah masakan ayam dengan cita rasa manis gurih dari kecap, dimasak bersama bawang dan cabai.",
    imageUrl: "images/ayamkecap.jpg",
    ingredients: [
      "500 gram ayam, potong",
      "5 sdm kecap manis",
      "1 buah bawang bombay, iris",
      "3 siung bawang putih, cincang",
      "5 buah cabai merah",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "200 ml air",
      "Minyak untuk menumis",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan cabai dan ayam, aduk hingga ayam berubah warna.",
      "Tambahkan kecap manis, garam, dan merica.",
      "Tuang air dan masak hingga ayam empuk dan kuah mengental.",
      "Angkat dan sajikan ayam kecap hangat.",
    ],
  ),

  Recipe(
    id: 40,
    title: "Tumis Buncis",
    description:
        "Tumis buncis adalah masakan sederhana dan praktis dengan rasa gurih dan segar.",
    imageUrl: "images/tumisbuncis.jpg",
    ingredients: [
      "200 gram buncis, potong",
      "3 siung bawang putih, iris",
      "5 buah cabai rawit",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak goreng di wajan.",
      "Tumis bawang putih dan cabai hingga harum.",
      "Masukkan buncis, aduk rata.",
      "Tambahkan garam dan gula.",
      "Masak hingga buncis matang namun tetap renyah.",
      "Angkat dan sajikan tumis buncis hangat.",
    ],
  ),

  Recipe(
    id: 41,
    title: "Ikan Goreng Sambal",
    description:
        "Ikan goreng renyah yang disajikan dengan sambal pedas segar, cocok sebagai lauk makan siang atau malam.",
    imageUrl: "images/ikangorengsambal.jpg",
    ingredients: [
      "1 ekor ikan (nila/kembung), bersihkan",
      "1 sdt air jeruk nipis",
      "1/2 sdt garam",
      "Minyak goreng secukupnya",

      // Sambal
      "8 buah cabai rawit merah",
      "2 buah cabai merah besar",
      "1 buah tomat",
      "1/2 sdt garam",
      "1/4 sdt gula",
    ],
    steps: [
      "Lumuri ikan dengan jeruk nipis dan garam, diamkan 10 menit.",
      "Panaskan minyak, goreng ikan hingga kuning keemasan dan renyah, tiriskan.",
      "Ulek cabai rawit, cabai merah, tomat, garam, dan gula hingga halus.",
      "Sajikan ikan goreng dengan sambal pedas di sampingnya.",
    ],
  ),

  Recipe(
    id: 42,
    title: "Perkedel Kentang",
    description:
        "Perkedel kentang yang lembut di dalam dan renyah di luar, cocok sebagai lauk pendamping.",
    imageUrl: "images/perkedel.jpg",
    ingredients: [
      "500 gram kentang, rebus dan haluskan",
      "1 butir telur",
      "2 batang daun bawang, iris halus",
      "1/2 sdt merica bubuk",
      "1/2 sdt garam",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Campur kentang halus dengan telur, daun bawang, merica, dan garam.",
      "Aduk hingga adonan tercampur rata.",
      "Bentuk adonan sesuai selera.",
      "Goreng dalam minyak panas hingga kecokelatan.",
      "Angkat dan tiriskan, sajikan hangat.",
    ],
  ),

  Recipe(
    id: 43,
    title: "Ayam Woku",
    description:
        "Ayam woku khas Manado dengan cita rasa pedas segar dan aroma rempah yang kuat.",
    imageUrl: "images/ayamwoku.jpg",
    ingredients: [
      "1 ekor ayam, potong-potong",
      "8 buah cabai merah",
      "6 buah cabai rawit",
      "6 siung bawang merah",
      "4 siung bawang putih",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "1 ikat daun kemangi",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan cabai merah, cabai rawit, bawang merah, dan bawang putih.",
      "Tumis bumbu halus hingga harum.",
      "Masukkan serai dan daun jeruk, aduk rata.",
      "Masukkan ayam, aduk hingga ayam berubah warna.",
      "Tambahkan sedikit air dan masak hingga ayam empuk.",
      "Masukkan daun kemangi, aduk sebentar.",
      "Koreksi rasa, angkat dan sajikan ayam woku hangat.",
    ],
  ),

  Recipe(
    id: 44,
    title: "Sambal Terasi",
    description:
        "Sambal terasi pedas dengan aroma khas terasi bakar, cocok sebagai pelengkap aneka lauk.",
    imageUrl: "images/sambalterasi.jpg",
    ingredients: [
      "10 buah cabai rawit",
      "2 buah cabai merah",
      "1 buah tomat",
      "1/2 sdt terasi bakar",
      "1/2 sdt garam",
      "1/4 sdt gula",
    ],
    steps: [
      "Bakar terasi dan tomat hingga harum.",
      "Ulek cabai rawit, cabai merah, terasi, dan tomat.",
      "Tambahkan garam dan gula, ulek hingga halus.",
      "Sajikan sambal terasi sebagai pelengkap.",
    ],
  ),

  Recipe(
    id: 45,
    title: "Bakmi Jawa",
    description:
        "Bakmi Jawa adalah mie khas Jawa dengan cita rasa gurih manis, dimasak menggunakan telur dan ayam suwir.",
    imageUrl: "images/bakmijawa.webp",
    ingredients: [
      "200 gram mie telur",
      "150 gram ayam suwir",
      "2 butir telur",
      "3 siung bawang putih",
      "2 batang daun bawang",
      "2 sdm kecap manis",
      "1 sdt kecap asin",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Rebus mie hingga setengah matang, tiriskan.",
      "Tumis bawang putih hingga harum.",
      "Masukkan telur, orak-arik hingga matang.",
      "Masukkan ayam suwir dan mie.",
      "Tambahkan kecap manis, kecap asin, garam, dan merica.",
      "Aduk hingga bumbu meresap dan mie matang.",
      "Masukkan daun bawang, aduk sebentar lalu angkat.",
      "Sajikan bakmi Jawa selagi hangat.",
    ],
  ),

  Recipe(
    id: 46,
    title: "Ayam Taliwang",
    description:
        "Ayam Taliwang adalah ayam bakar khas Lombok dengan bumbu pedas berbahan cabai merah dan terasi, bercita rasa gurih, pedas, dan beraroma khas.",
    imageUrl: "images/taliwang.png",
    ingredients: [
      "1 ekor ayam kampung muda, belah dua",
      "10 buah cabai merah keriting",
      "5 buah cabai rawit (sesuai selera)",
      "4 siung bawang putih",
      "1/2 sdt terasi bakar",
      "1 sdt garam",
      "1 sdt gula",
      "2 sdm minyak goreng",
      "1 sdm air jeruk nipis",
    ],
    steps: [
      "Lumuri ayam dengan air jeruk nipis dan garam, diamkan 10 menit.",
      "Haluskan cabai merah, cabai rawit, bawang putih, dan terasi.",
      "Tumis bumbu halus hingga harum dan matang.",
      "Lumuri ayam dengan bumbu hingga merata.",
      "Bakar ayam sambil dioles sisa bumbu hingga matang dan harum.",
      "Angkat dan sajikan ayam taliwang selagi panas.",
    ],
  ),

  Recipe(
    id: 47,
    title: "Soto Kudus",
    description:
        "Soto Kudus adalah soto ayam berkuah bening khas Jawa Tengah yang ringan, gurih, dan biasanya disajikan dalam mangkuk kecil.",
    imageUrl: "images/sotokudus.jpg",
    ingredients: [
      "1 ekor ayam, potong-potong",
      "2 liter air",
      "4 siung bawang putih",
      "2 cm jahe, geprek",
      "1 batang serai, memarkan",
      "2 lembar daun salam",
      "1 sdt garam",
      "1/2 sdt merica",
      "Kecambah/tauge pendek",
      "Daun bawang dan seledri",
      "Bawang goreng",
    ],
    steps: [
      "Rebus ayam hingga empuk, angkat ayam dan saring kuah.",
      "Suwir ayam, sisihkan.",
      "Tumis bawang putih hingga harum.",
      "Masukkan tumisan bawang, jahe, serai, dan daun salam ke dalam kuah.",
      "Bumbui garam dan merica, masak hingga kuah harum.",
      "Sajikan soto dengan suwiran ayam, kecambah, daun bawang, dan bawang goreng.",
    ],
  ),

  Recipe(
    id: 48,
    title: "Nasi Liwet Solo",
    description:
        "Nasi liwet khas Solo adalah nasi gurih yang dimasak dengan santan dan rempah, biasanya disajikan dengan ayam suwir, labu siam, dan areh.",
    imageUrl: "images/nasisololiwet.jpg",
    ingredients: [
      "2 cup beras",
      "500 ml santan",
      "2 batang serai, memarkan",
      "3 lembar daun salam",
      "1 sdt garam",
      "Air secukupnya",
      "Ayam suwir (pelengkap)",
      "Telur pindang (pelengkap)",
    ],
    steps: [
      "Cuci beras hingga bersih.",
      "Masukkan beras ke panci atau rice cooker.",
      "Tambahkan santan, air, serai, daun salam, dan garam.",
      "Masak hingga nasi matang dan harum.",
      "Aduk nasi liwet dan sajikan dengan lauk pelengkap.",
    ],
  ),

  Recipe(
    id: 49,
    title: "Ayam Goreng Kalasan",
    description:
        "Ayam Goreng Kalasan adalah ayam ungkep khas Yogyakarta dengan rasa manis gurih dari gula merah dan santan.",
    imageUrl: "images/ayamgorengkalasan.webp",
    ingredients: [
      "1 ekor ayam, potong-potong",
      "500 ml air kelapa atau santan encer",
      "3 siung bawang putih",
      "2 cm lengkuas",
      "2 lembar daun salam",
      "2 sdm gula merah serut",
      "1 sdt garam",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Rebus ayam bersama bawang putih, lengkuas, daun salam, gula merah, dan garam hingga empuk.",
      "Angkat ayam dan tiriskan.",
      "Goreng ayam dalam minyak panas hingga kecokelatan.",
      "Angkat dan sajikan ayam goreng Kalasan hangat.",
    ],
  ),

  Recipe(
    id: 50,
    title: "Sosis Solo",
    description:
        "Sosis Solo adalah jajanan khas Solo berupa dadar tipis berisi ayam cincang berbumbu gurih, digoreng hingga renyah.",
    imageUrl: "images/sosissolo.jpg",
    ingredients: [
      "200 gram daging ayam cincang",
      "2 siung bawang putih, cincang",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Kulit dadar telur",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Tumis bawang putih hingga harum.",
      "Masukkan ayam cincang, garam, dan merica, masak hingga matang.",
      "Ambil kulit dadar, isi dengan tumisan ayam.",
      "Gulung rapi seperti sosis.",
      "Goreng hingga kecokelatan.",
      "Angkat dan sajikan sosis Solo hangat.",
    ],
  ),

  Recipe(
    id: 51,
    title: "Ayam Pop",
    description:
        "Ayam Pop adalah hidangan khas Padang berupa ayam rebus berwarna putih pucat dengan rasa gurih ringan, biasanya disajikan dengan sambal dan nasi hangat.",
    imageUrl: "images/ayampop.webp",
    ingredients: [
      "1 ekor ayam kampung, potong-potong",
      "500 ml air kelapa",
      "4 siung bawang putih, geprek",
      "1 sdt garam",
      "1 sdt air jeruk nipis",
      "Minyak goreng secukupnya",
      "Sambal merah Padang (pelengkap)",
    ],
    steps: [
      "Lumuri ayam dengan air jeruk nipis, diamkan 10 menit.",
      "Rebus ayam bersama air kelapa, bawang putih, dan garam hingga empuk.",
      "Angkat ayam dan tiriskan.",
      "Goreng ayam sebentar saja dalam minyak panas (jangan sampai kecokelatan).",
      "Angkat dan sajikan ayam pop dengan sambal Padang.",
    ],
  ),

  Recipe(
    id: 52,
    title: "Tongseng Kambing",
    description:
        "Tongseng kambing adalah masakan berkuah kental dengan rasa manis pedas dan aroma rempah khas, populer di daerah Jawa Tengah.",
    imageUrl: "images/tongsengkambing.webp",
    ingredients: [
      "500 gram daging kambing, potong kecil",
      "200 gram kol, iris kasar",
      "2 batang daun bawang, iris",
      "5 sdm kecap manis",
      "500 ml air",
      "2 lembar daun salam",
      "2 batang serai, memarkan",

      // Bumbu halus
      "6 siung bawang merah",
      "4 siung bawang putih",
      "5 buah cabai merah",
      "2 cm jahe",
      "2 cm lengkuas",
      "1 sdt ketumbar bubuk",
      "1/2 sdt merica",
      "1 sdt garam",
    ],
    steps: [
      "Tumis bumbu halus hingga harum.",
      "Masukkan daun salam dan serai, aduk hingga wangi.",
      "Masukkan daging kambing, aduk hingga berubah warna.",
      "Tuangkan air dan masak hingga daging empuk.",
      "Tambahkan kecap manis, kol, dan daun bawang.",
      "Masak sebentar hingga kol layu.",
      "Koreksi rasa dan sajikan tongseng kambing selagi hangat.",
    ],
  ),

  Recipe(
    id: 53,
    title: "Tumis Terong Balado",
    description:
        "Tumis terong balado adalah olahan terong goreng yang dimasak dengan sambal balado pedas khas Minang.",
    imageUrl: "images/terongbalado.jpg",
    ingredients: [
      "3 buah terong ungu, potong-potong",
      "Minyak goreng secukupnya",

      // Sambal balado
      "8 buah cabai merah",
      "5 buah cabai rawit",
      "4 siung bawang merah",
      "3 siung bawang putih",
      "1 buah tomat",
      "1 sdt garam",
      "1/2 sdt gula",
    ],
    steps: [
      "Goreng potongan terong hingga matang, angkat dan tiriskan.",
      "Haluskan cabai merah, cabai rawit, bawang merah, bawang putih, dan tomat.",
      "Tumis sambal hingga matang dan harum.",
      "Masukkan terong goreng, aduk hingga sambal merata.",
      "Koreksi rasa lalu angkat dan sajikan.",
    ],
  ),

  Recipe(
    id: 54,
    title: "Ayam Lada Hitam",
    description:
        "Ayam lada hitam adalah masakan ayam dengan saus lada hitam yang gurih dan sedikit pedas, populer pada menu rumahan dan restoran.",
    imageUrl: "images/ayamlada.jpg",
    ingredients: [
      "500 gram ayam fillet, potong dadu",
      "1 buah bawang bombay, iris",
      "3 siung bawang putih, cincang",
      "1 sdm lada hitam tumbuk kasar",
      "2 sdm saus tiram",
      "1 sdm kecap manis",
      "200 ml air",
      "1 sdt maizena, larutkan",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan ayam, masak hingga berubah warna.",
      "Tambahkan lada hitam, saus tiram, kecap manis, dan air.",
      "Masak hingga ayam empuk.",
      "Masukkan larutan maizena, aduk hingga saus mengental.",
      "Angkat dan sajikan ayam lada hitam selagi hangat.",
    ],
  ),

  Recipe(
    id: 55,
    title: "Tempe Bacem",
    description:
        "Tempe bacem adalah masakan khas Jawa dengan cita rasa manis gurih, dimasak menggunakan gula merah dan kecap.",
    imageUrl: "images/tempebacem.jpg",
    ingredients: [
      "1 papan tempe, potong",
      "3 siung bawang putih",
      "2 lembar daun salam",
      "2 cm lengkuas",
      "3 sdm gula merah serut",
      "2 sdm kecap manis",
      "1/2 sdt garam",
      "500 ml air",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Rebus tempe bersama bawang putih, daun salam, lengkuas, gula merah, kecap, dan garam hingga air menyusut.",
      "Diamkan tempe agar bumbu meresap.",
      "Goreng tempe sebentar hingga permukaannya kecokelatan.",
      "Angkat dan sajikan tempe bacem hangat.",
    ],
  ),

  Recipe(
    id: 56,
    title: "Ayam Saus BBQ",
    description:
        "Ayam saus BBQ adalah hidangan ayam panggang dengan saus barbeque manis gurih dan aroma smoky yang menggugah selera.",
    imageUrl: "images/ayambbq.jpg",
    ingredients: [
      "500 gram ayam (paha/dada), potong sesuai selera",
      "5 sdm saus BBQ",
      "3 siung bawang putih, cincang",
      "1 buah bawang bombay, iris",
      "1 sdt garam",
      "1/2 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Lumuri ayam dengan garam dan merica, diamkan 15 menit.",
      "Tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan saus BBQ, aduk rata.",
      "Lumuri ayam dengan saus BBQ.",
      "Panggang ayam di oven atau teflon hingga matang dan berwarna kecokelatan.",
      "Sajikan ayam saus BBQ selagi hangat.",
    ],
  ),

  Recipe(
    id: 57,
    title: "Sup Misoa",
    description:
        "Sup misoa adalah sup hangat dengan tekstur lembut, berisi ayam suwir dan kuah kaldu ringan yang cocok disantap saat cuaca dingin.",
    imageUrl: "images/supmisoa.jpg",
    ingredients: [
      "1 ikat misoa",
      "200 gram ayam, rebus dan suwir",
      "1 liter kaldu ayam",
      "3 siung bawang putih, cincang",
      "1 batang daun bawang, iris",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Panaskan sedikit minyak, tumis bawang putih hingga harum.",
      "Masukkan kaldu ayam, masak hingga mendidih.",
      "Masukkan ayam suwir, garam, dan merica.",
      "Masukkan misoa, masak sebentar hingga misoa lunak.",
      "Tambahkan daun bawang, aduk sebentar.",
      "Angkat dan sajikan sup misoa hangat.",
    ],
  ),

  Recipe(
    id: 58,
    title: "Tempe Orek Basah",
    description:
        "Tempe orek basah adalah olahan tempe dengan bumbu kecap manis gurih dan tekstur lembut berkuah.",
    imageUrl: "images/tempeorekbasah.jpg",
    ingredients: [
      "1 papan tempe, potong korek api",
      "3 siung bawang putih, cincang",
      "4 siung bawang merah, iris",
      "3 sdm kecap manis",
      "1 sdt kecap asin",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "200 ml air",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang merah dan bawang putih hingga harum.",
      "Masukkan tempe, aduk rata.",
      "Tambahkan kecap manis, kecap asin, garam, dan gula.",
      "Tuang air dan masak hingga bumbu meresap dan kuah menyusut.",
      "Angkat dan sajikan tempe orek basah hangat.",
    ],
  ),

  Recipe(
    id: 59,
    title: "Ayam Panggang Madu",
    description:
        "Ayam panggang madu adalah ayam dengan cita rasa manis gurih dari madu dan kecap, dipanggang hingga caramelized.",
    imageUrl: "images/ayammadu.jpg",
    ingredients: [
      "600 gram ayam",
      "3 sdm madu",
      "2 sdm kecap manis",
      "3 siung bawang putih, haluskan",
      "1 sdt garam",
      "1/2 sdt merica",
    ],
    steps: [
      "Campur madu, kecap manis, bawang putih, garam, dan merica.",
      "Lumuri ayam dengan bumbu hingga merata, diamkan 30 menit.",
      "Panggang ayam sambil dibalik dan dioles sisa bumbu.",
      "Masak hingga ayam matang dan berwarna kecokelatan.",
      "Sajikan ayam panggang madu selagi hangat.",
    ],
  ),

  Recipe(
    id: 60,
    title: "Sup Kacang Merah",
    description:
        "Sup kacang merah adalah hidangan berkuah hangat dengan rasa gurih manis alami dari kacang merah dan sayuran.",
    imageUrl: "images/supkacangmerah.jpg",
    ingredients: [
      "200 gram kacang merah, rendam semalaman",
      "1 buah wortel, potong dadu",
      "1 liter kaldu sapi/ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang seledri",
    ],
    steps: [
      "Rebus kacang merah hingga empuk, tiriskan.",
      "Didihkan kaldu, masukkan bawang putih.",
      "Masukkan kacang merah dan wortel.",
      "Bumbui garam dan merica.",
      "Masak hingga semua bahan empuk.",
      "Tambahkan seledri, angkat dan sajikan hangat.",
    ],
  ),

  Recipe(
    id: 61,
    title: "Tumis Pare",
    description:
        "Tumis pare yang diolah dengan teknik khusus agar tidak pahit, dipadukan dengan telur sehingga rasanya gurih dan lezat.",
    imageUrl: "images/tumispare.jpg",
    ingredients: [
      "2 buah pare, belah dua dan iris tipis",
      "1 butir telur",
      "3 siung bawang putih, iris",
      "2 siung bawang merah, iris",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Remas pare dengan sedikit garam, bilas dengan air hingga bersih untuk mengurangi rasa pahit.",
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan telur, orak-arik hingga setengah matang.",
      "Masukkan pare, aduk rata.",
      "Tambahkan garam dan gula, masak hingga pare matang.",
      "Angkat dan sajikan tumis pare selagi hangat.",
    ],
  ),

  Recipe(
    id: 62,
    title: "Tahu Bacem",
    description:
        "Tahu bacem khas Jawa dengan cita rasa manis gurih, dimasak bersama gula merah dan kecap hingga bumbu meresap.",
    imageUrl: "images/tahubacem.jpg",
    ingredients: [
      "10 buah tahu putih",
      "4 siung bawang putih",
      "2 lembar daun salam",
      "2 cm lengkuas, memarkan",
      "4 sdm gula merah serut",
      "3 sdm kecap manis",
      "1/2 sdt garam",
      "500 ml air",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Rebus tahu bersama bawang putih, daun salam, lengkuas, gula merah, kecap, dan garam hingga air menyusut.",
      "Diamkan tahu agar bumbu meresap.",
      "Goreng tahu sebentar hingga bagian luarnya kecokelatan.",
      "Angkat dan sajikan tahu bacem hangat.",
    ],
  ),

  Recipe(
    id: 63,
    title: "Sayur Lodeh",
    description:
        "Sayur lodeh adalah masakan berkuah santan dengan aneka sayuran, bercita rasa gurih dan khas masakan rumahan.",
    imageUrl: "images/sayurlodeh.jpg",
    ingredients: [
      "800 ml santan",
      "1 buah terong, potong",
      "1 buah labu siam, potong",
      "100 gram kacang panjang, potong",
      "3 siung bawang merah",
      "2 siung bawang putih",
      "2 butir kemiri",
      "2 cm lengkuas",
      "2 lembar daun salam",
      "1 sdt garam",
      "1/2 sdt gula",
      "Minyak untuk menumis",
    ],
    steps: [
      "Haluskan bawang merah, bawang putih, dan kemiri.",
      "Tumis bumbu halus hingga harum.",
      "Masukkan lengkuas dan daun salam.",
      "Tuangkan santan, masak dengan api kecil sambil diaduk.",
      "Masukkan semua sayuran.",
      "Bumbui garam dan gula.",
      "Masak hingga sayuran empuk dan kuah gurih.",
      "Angkat dan sajikan sayur lodeh hangat.",
    ],
  ),

  Recipe(
    id: 64,
    title: "Telur Dadar Padang",
    description:
        "Telur dadar Padang terkenal dengan teksturnya yang tebal, renyah di luar, dan kaya rasa rempah.",
    imageUrl: "images/telurdadarpadang.jpg",
    ingredients: [
      "4 butir telur",
      "2 batang daun bawang, iris",
      "5 buah cabai merah, iris",
      "2 siung bawang merah, iris",
      "1 sdt tepung beras",
      "1/2 sdt garam",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Kocok telur bersama daun bawang, cabai, bawang merah, tepung beras, dan garam.",
      "Panaskan minyak agak banyak di wajan.",
      "Tuang adonan telur, masak dengan api sedang.",
      "Balik telur dan goreng hingga matang dan tebal.",
      "Angkat dan sajikan telur dadar Padang hangat.",
    ],
  ),

  Recipe(
    id: 65,
    title: "Tumis Tahu Jamur",
    description:
        "Tumis tahu jamur adalah masakan sederhana dan sehat dengan rasa gurih alami dari tahu dan jamur.",
    imageUrl: "images/tahujamur.jpg",
    ingredients: [
      "5 buah tahu putih, potong dadu",
      "200 gram jamur tiram, suwir",
      "3 siung bawang putih, cincang",
      "2 siung bawang merah, iris",
      "1 sdm saus tiram",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan tahu, aduk hingga sedikit kecokelatan.",
      "Masukkan jamur, aduk rata.",
      "Tambahkan saus tiram, garam, dan merica.",
      "Masak hingga semua bahan matang dan bumbu meresap.",
      "Angkat dan sajikan tumis tahu jamur hangat.",
    ],
  ),

  Recipe(
    id: 66,
    title: "Perkedel Jagung",
    description:
        "Perkedel jagung atau bakwan jagung yang gurih dan renyah, cocok sebagai lauk atau camilan.",
    imageUrl: "images/perkedeljagung.jpg",
    ingredients: [
      "2 buah jagung manis, pipil dan haluskan kasar",
      "1 butir telur",
      "3 sdm tepung terigu",
      "2 siung bawang putih, haluskan",
      "1 batang daun bawang, iris",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Campur jagung, telur, tepung, bawang putih, daun bawang, garam, dan merica.",
      "Aduk hingga adonan tercampur rata.",
      "Panaskan minyak, ambil satu sendok adonan.",
      "Goreng hingga kuning keemasan dan matang.",
      "Angkat dan sajikan hangat.",
    ],
  ),

  Recipe(
    id: 67,
    title: "Sayur Bayam",
    description:
        "Sayur bening bayam sederhana dengan rasa segar dan ringan, cocok untuk menu sehari-hari.",
    imageUrl: "images/sayurbayam.jpg",
    ingredients: [
      "1 ikat bayam, petik daunnya",
      "1 buah jagung manis, potong",
      "3 siung bawang merah, iris",
      "1/2 sdt garam",
      "700 ml air",
    ],
    steps: [
      "Didihkan air dalam panci.",
      "Masukkan bawang merah dan jagung, rebus hingga jagung empuk.",
      "Masukkan bayam dan garam.",
      "Masak sebentar hingga bayam layu.",
      "Angkat dan sajikan hangat.",
    ],
  ),

  Recipe(
    id: 68,
    title: "Ayam Teriyaki",
    description:
        "Ayam teriyaki dengan saus manis gurih khas Jepang, dimasak bersama bawang bombay.",
    imageUrl: "images/ayamteriyaki.jpg",
    ingredients: [
      "500 gram ayam fillet, potong dadu",
      "1 buah bawang bombay, iris",
      "4 sdm saus teriyaki",
      "2 siung bawang putih, cincang",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih hingga harum.",
      "Masukkan bawang bombay, tumis hingga layu.",
      "Masukkan ayam, masak hingga berubah warna.",
      "Tambahkan saus teriyaki, garam, dan merica.",
      "Masak hingga ayam matang dan saus mengental.",
      "Angkat dan sajikan ayam teriyaki hangat.",
    ],
  ),

  Recipe(
    id: 69,
    title: "Tumis Jamur Crispy",
    description:
        "Jamur crispy yang digoreng renyah dan gurih, cocok sebagai lauk atau camilan.",
    imageUrl: "images/jamurcrispy.jpg",
    ingredients: [
      "200 gram jamur tiram",
      "5 sdm tepung bumbu serbaguna",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Suwir jamur dan cuci bersih, tiriskan.",
      "Balur jamur dengan tepung bumbu, garam, dan merica.",
      "Panaskan minyak, goreng jamur hingga renyah.",
      "Angkat dan tiriskan.",
      "Sajikan jamur crispy selagi hangat.",
    ],
  ),

  Recipe(
    id: 70,
    title: "Sup Wortel Kentang",
    description:
        "Sup wortel kentang sederhana dengan kuah bening gurih dan menyehatkan.",
    imageUrl: "images/supwortel.jpg",
    ingredients: [
      "2 buah wortel, potong",
      "2 buah kentang, potong dadu",
      "1 liter kaldu ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang daun bawang",
    ],
    steps: [
      "Didihkan kaldu ayam.",
      "Masukkan bawang putih, wortel, dan kentang.",
      "Masak hingga sayuran empuk.",
      "Tambahkan garam dan merica.",
      "Masukkan daun bawang, aduk sebentar.",
      "Angkat dan sajikan sup hangat.",
    ],
  ),

  Recipe(
    id: 71,
    title: "Sup Bihun Ayam",
    description:
        "Sup bihun ayam adalah hidangan berkuah bening yang ringan dan gurih, berisi bihun lembut dan ayam suwir.",
    imageUrl: "images/supbihun.jpg",
    ingredients: [
      "100 gram bihun, rendam air panas",
      "200 gram ayam, rebus dan suwir",
      "1 liter kaldu ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang daun bawang, iris",
      "1 batang seledri, iris",
      "Bawang goreng (pelengkap)",
    ],
    steps: [
      "Didihkan kaldu ayam bersama bawang putih.",
      "Masukkan ayam suwir, garam, dan merica.",
      "Masukkan bihun, masak sebentar hingga lembut.",
      "Tambahkan daun bawang dan seledri.",
      "Angkat dan sajikan sup bihun ayam dengan bawang goreng.",
    ],
  ),

  Recipe(
    id: 72,
    title: "Tumis Kacang Panjang",
    description:
        "Tumis kacang panjang sederhana dengan bawang dan cabai, gurih dan cocok untuk lauk harian.",
    imageUrl: "images/tumiskacangpanjang.jpg",
    ingredients: [
      "200 gram kacang panjang, potong",
      "3 siung bawang putih, iris",
      "2 siung bawang merah, iris",
      "5 buah cabai rawit",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan cabai rawit dan kacang panjang.",
      "Aduk rata dan tambahkan garam serta gula.",
      "Masak hingga kacang panjang matang namun tetap renyah.",
      "Angkat dan sajikan tumis kacang panjang hangat.",
    ],
  ),

  Recipe(
    id: 73,
    title: "Sup Tomyam Ayam",
    description:
        "Sup tomyam ayam dengan rasa asam, pedas, dan segar khas Thailand.",
    imageUrl: "images/tomyamayam.jpg",
    ingredients: [
      "300 gram ayam, potong kecil",
      "1 liter air",
      "2 batang serai, memarkan",
      "3 lembar daun jeruk",
      "3 cm lengkuas, iris",
      "5 buah cabai rawit",
      "2 sdm air jeruk nipis",
      "1 sdm saus ikan",
      "1/2 sdt garam",
      "Jamur (opsional)",
    ],
    steps: [
      "Didihkan air, masukkan serai, daun jeruk, dan lengkuas.",
      "Masukkan ayam, masak hingga ayam matang.",
      "Tambahkan cabai rawit, saus ikan, dan garam.",
      "Masukkan jamur bila pakai.",
      "Matikan api, tambahkan air jeruk nipis.",
      "Aduk rata dan sajikan tomyam ayam hangat.",
    ],
  ),

  Recipe(
    id: 74,
    title: "Sup Telur Puyuh",
    description:
        "Sup telur puyuh dengan sayuran dan kuah bening gurih, cocok untuk menu keluarga.",
    imageUrl: "images/suptelurpuyuh.jpg",
    ingredients: [
      "10 butir telur puyuh, rebus dan kupas",
      "1 buah wortel, iris",
      "1 liter kaldu ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang daun bawang",
    ],
    steps: [
      "Didihkan kaldu ayam dengan bawang putih.",
      "Masukkan wortel, masak hingga empuk.",
      "Masukkan telur puyuh.",
      "Tambahkan garam dan merica.",
      "Masak sebentar hingga semua bahan panas.",
      "Angkat dan sajikan sup telur puyuh hangat.",
    ],
  ),

  Recipe(
    id: 75,
    title: "Tumis Pakcoy",
    description:
        "Tumis pakcoy bawang putih yang simpel, cepat dimasak, dan tetap segar.",
    imageUrl: "images/tumispakcoy.jpg",
    ingredients: [
      "2 ikat pakcoy, potong",
      "3 siung bawang putih, cincang",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih hingga harum.",
      "Masukkan pakcoy, aduk cepat.",
      "Tambahkan garam dan merica.",
      "Masak sebentar hingga pakcoy layu tapi tetap hijau.",
      "Angkat dan sajikan tumis pakcoy hangat.",
    ],
  ),

  Recipe(
    id: 76,
    title: "Sup Jamur Enoki",
    description:
        "Sup jamur enoki adalah sup ringan dan sehat dengan kuah bening gurih, cocok untuk menu harian.",
    imageUrl: "images/supenoki.jpg",
    ingredients: [
      "1 bungkus jamur enoki, potong akar dan cuci bersih",
      "1 liter kaldu ayam/sayur",
      "3 siung bawang putih, geprek",
      "1 batang daun bawang, iris",
      "1/2 sdt garam",
      "1/4 sdt merica",
    ],
    steps: [
      "Didihkan kaldu dalam panci.",
      "Masukkan bawang putih, masak hingga harum.",
      "Masukkan jamur enoki.",
      "Bumbui dengan garam dan merica.",
      "Masak sebentar hingga jamur layu.",
      "Tambahkan daun bawang, aduk, lalu angkat.",
      "Sajikan sup jamur enoki hangat.",
    ],
  ),

  Recipe(
    id: 77,
    title: "Tumis Kangkung Terasi",
    description:
        "Tumis kangkung terasi dengan aroma khas terasi yang kuat dan rasa gurih pedas.",
    imageUrl: "images/kangkungterasi.jpg",
    ingredients: [
      "1 ikat kangkung, petik dan cuci bersih",
      "2 siung bawang putih, iris",
      "3 siung bawang merah, iris",
      "5 buah cabai rawit",
      "1/2 sdt terasi bakar",
      "1/2 sdt garam",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan cabai dan terasi, tumis hingga wangi.",
      "Masukkan kangkung, aduk cepat.",
      "Tambahkan garam dan aduk rata.",
      "Masak sebentar hingga kangkung layu.",
      "Angkat dan sajikan tumis kangkung terasi hangat.",
    ],
  ),

  Recipe(
    id: 78,
    title: "Tumis Buncis Telur",
    description:
        "Tumis buncis telur sederhana dengan rasa gurih, praktis untuk menu sehari-hari.",
    imageUrl: "images/tumisbuncistelur.jpg",
    ingredients: [
      "200 gram buncis, potong",
      "2 butir telur",
      "3 siung bawang putih, iris",
      "2 siung bawang merah, iris",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan telur, orak-arik hingga setengah matang.",
      "Masukkan buncis, aduk rata.",
      "Tambahkan garam dan merica.",
      "Masak hingga buncis matang.",
      "Angkat dan sajikan tumis buncis telur hangat.",
    ],
  ),

  Recipe(
    id: 79,
    title: "Sup Oyong Bakso",
    description:
        "Sup oyong bakso dengan kuah bening segar, cocok untuk menu rumahan yang ringan.",
    imageUrl: "images/supoyongbakso.jpg",
    ingredients: [
      "2 buah oyong/gambas, kupas dan iris",
      "8 butir bakso sapi, belah dua",
      "1 liter kaldu ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang daun bawang",
    ],
    steps: [
      "Didihkan kaldu ayam bersama bawang putih.",
      "Masukkan bakso, masak hingga mengapung.",
      "Masukkan oyong, masak sebentar hingga lunak.",
      "Tambahkan garam dan merica.",
      "Masukkan daun bawang, aduk sebentar.",
      "Angkat dan sajikan sup oyong bakso hangat.",
    ],
  ),

  Recipe(
    id: 80,
    title: "Tumis Terong Hijau",
    description:
        "Tumis terong hijau sederhana dengan rasa gurih, cocok sebagai lauk pendamping.",
    imageUrl: "images/teronghijau.jpg",
    ingredients: [
      "3 buah terong hijau, potong-potong",
      "3 siung bawang putih, iris",
      "2 siung bawang merah, iris",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan terong hijau, aduk rata.",
      "Tambahkan garam dan gula.",
      "Masak hingga terong empuk dan matang.",
      "Angkat dan sajikan tumis terong hijau hangat.",
    ],
  ),

  Recipe(
    id: 81,
    title: "Tumis Daun Singkong",
    description:
        "Tumis daun singkong pedas dengan aroma bawang dan cabai, gurih dan cocok sebagai lauk rumahan.",
    imageUrl: "images/daunsingkong.jpg",
    ingredients: [
      "1 ikat daun singkong, rebus dan peras",
      "3 siung bawang putih, iris",
      "4 siung bawang merah, iris",
      "5 buah cabai rawit",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Rebus daun singkong hingga empuk, tiriskan dan peras airnya.",
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan cabai rawit, tumis sebentar.",
      "Masukkan daun singkong, aduk rata.",
      "Tambahkan garam dan gula, masak hingga bumbu meresap.",
      "Angkat dan sajikan tumis daun singkong hangat.",
    ],
  ),

  Recipe(
    id: 82,
    title: "Tumis Tofu Jepang",
    description:
        "Tumis tofu Jepang yang lembut dengan rasa gurih ringan ala masakan Asia.",
    imageUrl: "images/tofujepang.jpg",
    ingredients: [
      "2 buah tofu Jepang, potong tebal",
      "3 siung bawang putih, cincang",
      "1 buah bawang bombay kecil, iris",
      "2 sdm saus tiram",
      "1 sdt kecap asin",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan tofu Jepang dengan hati-hati agar tidak hancur.",
      "Tambahkan saus tiram, kecap asin, dan merica.",
      "Aduk perlahan hingga tofu terbalut saus.",
      "Masak sebentar lalu angkat.",
      "Sajikan tumis tofu Jepang selagi hangat.",
    ],
  ),

  Recipe(
    id: 83,
    title: "Sup Sawi Hijau",
    description:
        "Sup sawi hijau dengan kuah bening segar, dilengkapi bakso untuk rasa gurih.",
    imageUrl: "images/supsawihijau.jpg",
    ingredients: [
      "1 ikat sawi hijau, potong",
      "8 butir bakso sapi, belah dua",
      "1 liter kaldu ayam",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "1 batang daun bawang",
    ],
    steps: [
      "Didihkan kaldu ayam bersama bawang putih.",
      "Masukkan bakso, masak hingga panas.",
      "Masukkan sawi hijau, masak sebentar hingga layu.",
      "Tambahkan garam dan merica.",
      "Masukkan daun bawang, aduk sebentar.",
      "Angkat dan sajikan sup sawi hijau hangat.",
    ],
  ),

  Recipe(
    id: 84,
    title: "Tumis Jagung Manis",
    description:
        "Tumis jagung manis sederhana dengan rasa gurih dan sedikit manis alami.",
    imageUrl: "images/tumisjagung.jpg",
    ingredients: [
      "2 buah jagung manis, pipil",
      "3 siung bawang putih, cincang",
      "1 sdm mentega",
      "1/2 sdt garam",
      "1/4 sdt gula",
    ],
    steps: [
      "Lelehkan mentega di wajan.",
      "Tumis bawang putih hingga harum.",
      "Masukkan jagung manis, aduk rata.",
      "Tambahkan garam dan gula.",
      "Masak hingga jagung matang dan harum.",
      "Angkat dan sajikan tumis jagung manis hangat.",
    ],
  ),

  Recipe(
    id: 85,
    title: "Sup Brokoli",
    description:
        "Sup brokoli sehat dan ringan dengan kuah bening gurih, cocok untuk menu diet.",
    imageUrl: "images/supbrokoli.jpg",
    ingredients: [
      "1 bonggol brokoli, potong per kuntum",
      "1 buah wortel, iris",
      "1 liter kaldu ayam/sayur",
      "3 siung bawang putih, geprek",
      "1/2 sdt garam",
      "1/4 sdt merica",
    ],
    steps: [
      "Didihkan kaldu bersama bawang putih.",
      "Masukkan wortel, masak hingga setengah empuk.",
      "Masukkan brokoli.",
      "Tambahkan garam dan merica.",
      "Masak sebentar hingga brokoli matang tapi tetap hijau.",
      "Angkat dan sajikan sup brokoli hangat.",
    ],
  ),

  Recipe(
    id: 86,
    title: "Tumis Jamur Kuping",
    description:
        "Tumis jamur kuping gurih dengan tekstur kenyal dan rasa sederhana, cocok sebagai lauk pendamping.",
    imageUrl: "images/jamurkuping.jpg",
    ingredients: [
      "200 gram jamur kuping kering, rendam dan iris",
      "3 siung bawang putih, cincang",
      "2 siung bawang merah, iris",
      "2 sdm kecap manis",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Rendam jamur kuping hingga mengembang, cuci bersih lalu iris.",
      "Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.",
      "Masukkan jamur kuping, aduk rata.",
      "Tambahkan kecap manis, garam, dan merica.",
      "Masak hingga jamur matang dan bumbu meresap.",
      "Angkat dan sajikan tumis jamur kuping hangat.",
    ],
  ),

  Recipe(
    id: 87,
    title: "Ayam Saus Padang",
    description:
        "Ayam saus Padang dengan rasa pedas manis khas, berpadu saus kental yang menggugah selera.",
    imageUrl: "images/ayampadang.jpg",
    ingredients: [
      "500 gram ayam, potong dadu",
      "3 siung bawang putih, cincang",
      "1 buah bawang bombay, iris",
      "6 buah cabai merah, haluskan",
      "3 sdm saus tomat",
      "2 sdm saus sambal",
      "1 sdt gula",
      "1/2 sdt garam",
      "200 ml air",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Goreng ayam hingga matang, tiriskan.",
      "Panaskan sedikit minyak, tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan cabai halus, saus tomat, dan saus sambal, aduk rata.",
      "Tambahkan air, gula, dan garam, masak hingga saus mengental.",
      "Masukkan ayam goreng, aduk hingga ayam terbalut saus.",
      "Angkat dan sajikan ayam saus Padang hangat.",
    ],
  ),

  Recipe(
    id: 88,
    title: "Ayam Saus Blackpepper",
    description:
        "Ayam saus blackpepper dengan rasa pedas hangat dari lada hitam dan saus kental yang gurih.",
    imageUrl: "images/ayamblackpepper.jpg",
    ingredients: [
      "500 gram ayam fillet, potong dadu",
      "1 buah bawang bombay, iris",
      "3 siung bawang putih, cincang",
      "1 sdm lada hitam tumbuk kasar",
      "2 sdm saus tiram",
      "1 sdm kecap manis",
      "200 ml air",
      "1 sdt maizena, larutkan",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih hingga harum.",
      "Masukkan bawang bombay, tumis hingga layu.",
      "Masukkan ayam, masak hingga berubah warna.",
      "Tambahkan lada hitam, saus tiram, dan kecap manis.",
      "Tuang air, masak hingga ayam empuk.",
      "Masukkan larutan maizena, aduk hingga saus mengental.",
      "Angkat dan sajikan ayam saus blackpepper hangat.",
    ],
  ),

  Recipe(
    id: 89,
    title: "Tumis Jamur Enoki Pedas",
    description:
        "Tumis jamur enoki pedas dengan cita rasa gurih dan segar, cocok untuk menu sederhana.",
    imageUrl: "images/enokipedas.jpg",
    ingredients: [
      "1 bungkus jamur enoki, potong akar dan cuci bersih",
      "4 siung bawang putih, cincang",
      "5 buah cabai rawit, iris",
      "2 sdm saus tiram",
      "1/2 sdt garam",
      "1/4 sdt gula",
      "2 sdm minyak goreng",
    ],
    steps: [
      "Panaskan minyak, tumis bawang putih hingga harum.",
      "Masukkan cabai rawit, tumis sebentar.",
      "Masukkan jamur enoki, aduk rata.",
      "Tambahkan saus tiram, garam, dan gula.",
      "Masak hingga jamur layu dan bumbu meresap.",
      "Angkat dan sajikan tumis jamur enoki pedas hangat.",
    ],
  ),

  Recipe(
    id: 90,
    title: "Klepon",
    description:
        "Klepon adalah kue tradisional berbahan tepung ketan berisi gula merah cair dan dibalut kelapa parut.",
    imageUrl: "images/klepon.jpg",
    ingredients: [
      "250 gram tepung ketan",
      "1/2 sdt garam",
      "Air pandan secukupnya",
      "100 gram gula merah, serut halus",
      "100 gram kelapa parut kukus",
    ],
    steps: [
      "Campur tepung ketan, garam, dan air pandan hingga bisa dipulung.",
      "Ambil sedikit adonan, isi gula merah, lalu bulatkan.",
      "Rebus air hingga mendidih, masukkan klepon.",
      "Masak hingga klepon mengapung, angkat dan tiriskan.",
      "Gulingkan klepon ke kelapa parut.",
      "Sajikan klepon siap dinikmati.",
    ],
  ),

  Recipe(
    id: 91,
    title: "Es Campur",
    description:
        "Es campur adalah minuman segar khas Indonesia yang berisi aneka buah, jelly, dan sirup manis, cocok dinikmati saat cuaca panas.",
    imageUrl: "images/escampur.jpg",
    ingredients: [
      "Semangka, potong dadu",
      "Melon, potong dadu",
      "Nanas, potong kecil",
      "Agar-agar/jelly, potong dadu",
      "2 sdm susu kental manis",
      "3 sdm sirup cocopandan",
      "Es batu serut",
    ],
    steps: [
      "Siapkan mangkuk saji.",
      "Masukkan potongan buah dan jelly.",
      "Tambahkan es batu serut.",
      "Tuang susu kental manis dan sirup.",
      "Aduk rata dan sajikan es campur dingin.",
    ],
  ),

  Recipe(
    id: 92,
    title: "Otak-Otak Goreng",
    description:
        "Otak-otak goreng adalah camilan gurih berbahan ikan yang digoreng hingga renyah di luar dan lembut di dalam.",
    imageUrl: "images/otakotakgoreng.jpg",
    ingredients: [
      "300 gram daging ikan tenggiri giling",
      "150 gram tepung tapioka",
      "2 siung bawang putih, haluskan",
      "1 butir telur",
      "1/2 sdt garam",
      "1/2 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Campur ikan giling, tepung, bawang putih, telur, garam, dan merica.",
      "Aduk hingga adonan kalis.",
      "Bentuk adonan memanjang atau bulat.",
      "Panaskan minyak, goreng otak-otak hingga kuning keemasan.",
      "Angkat dan tiriskan, sajikan hangat.",
    ],
  ),

  Recipe(
    id: 93,
    title: "Onde-Onde",
    description:
        "Onde-onde adalah kue tradisional berbahan tepung ketan dengan isian kacang hijau manis dan balutan wijen.",
    imageUrl: "images/ondeonde.jpg",
    ingredients: [
      "250 gram tepung ketan",
      "150 gram kacang hijau kupas, kukus dan haluskan",
      "100 gram gula pasir",
      "Wijen secukupnya",
      "Air hangat secukupnya",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Campur kacang hijau halus dengan gula, aduk rata.",
      "Campur tepung ketan dengan air hingga bisa dipulung.",
      "Ambil adonan, isi dengan kacang hijau, bulatkan.",
      "Gulingkan onde-onde ke wijen hingga rata.",
      "Goreng dalam minyak panas dengan api kecil hingga mengembang.",
      "Angkat dan tiriskan, sajikan onde-onde hangat.",
    ],
  ),

  Recipe(
    id: 94,
    title: "Risol Mayo",
    description:
        "Risol mayo adalah camilan modern berisi sosis, telur, dan mayones dengan kulit renyah.",
    imageUrl: "images/risolesmayo.jpg",
    ingredients: [
      "Kulit risoles siap pakai",
      "Sosis, potong kecil",
      "Telur rebus, potong",
      "Mayones secukupnya",
      "Tepung panir",
      "Putih telur",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Isi kulit risoles dengan sosis, telur, dan mayones.",
      "Gulung dan rekatkan ujungnya.",
      "Celupkan risoles ke putih telur lalu balur tepung panir.",
      "Goreng dalam minyak panas hingga kuning keemasan.",
      "Angkat dan sajikan risol mayo hangat.",
    ],
  ),

  Recipe(
    id: 95,
    title: "Pukis",
    description:
        "Kue pukis adalah kue tradisional berbahan dasar santan dan telur, bertekstur lembut dan manis.",
    imageUrl: "images/pukis.jpg",
    ingredients: [
      "250 gram tepung terigu",
      "3 butir telur",
      "150 gram gula pasir",
      "200 ml santan hangat",
      "1 sdt ragi instan",
      "1/2 sdt vanili",
      "Mentega dan topping secukupnya",
    ],
    steps: [
      "Kocok telur dan gula hingga larut.",
      "Masukkan ragi, vanili, dan santan hangat, aduk rata.",
      "Masukkan tepung terigu, aduk hingga adonan halus.",
      "Diamkan adonan sekitar 30 menit hingga mengembang.",
      "Tuang adonan ke cetakan pukis, masak hingga setengah matang.",
      "Tambahkan topping, tutup dan masak hingga matang.",
      "Angkat dan sajikan kue pukis hangat.",
    ],
  ),

  Recipe(
    id: 96,
    title: "Serabi",
    description:
        "Serabi adalah kue tradisional berbahan santan dengan tekstur lembut dan aroma khas, biasanya disajikan dengan kuah kinca.",
    imageUrl: "images/serabi.jpg",
    ingredients: [
      "200 gram tepung beras",
      "50 gram tepung terigu",
      "400 ml santan hangat",
      "1 sdt ragi instan",
      "1/2 sdt garam",
      "1 sdm gula pasir",
      "Minyak untuk olesan cetakan",
    ],
    steps: [
      "Campur tepung beras, tepung terigu, ragi, gula, dan garam.",
      "Tuang santan hangat sedikit demi sedikit sambil diaduk hingga rata.",
      "Diamkan adonan selama 30–45 menit hingga sedikit berbuih.",
      "Panaskan cetakan serabi dan olesi tipis minyak.",
      "Tuang adonan, masak dengan api kecil hingga matang.",
      "Angkat dan sajikan serabi hangat.",
    ],
  ),

  Recipe(
    id: 97,
    title: "Getuk",
    description:
        "Getuk adalah jajanan tradisional dari singkong yang dihaluskan dan diberi gula, disajikan dengan taburan kelapa parut.",
    imageUrl: "images/getuk.jpg",
    ingredients: [
      "1 kg singkong, kupas dan potong",
      "150 gram gula pasir atau gula merah",
      "1/4 sdt garam",
      "Kelapa parut kukus secukupnya",
      "Pewarna makanan (opsional)",
    ],
    steps: [
      "Rebus singkong hingga empuk, tiriskan.",
      "Haluskan singkong saat masih hangat.",
      "Tambahkan gula dan garam, aduk rata.",
      "Beri pewarna bila suka, lalu bentuk sesuai selera.",
      "Sajikan getuk dengan taburan kelapa parut.",
    ],
  ),

  Recipe(
    id: 98,
    title: "Bolu Kukus",
    description:
        "Bolu kukus adalah kue sederhana yang lembut dan mengembang, dimasak dengan cara dikukus.",
    imageUrl: "images/bolukukus.jpg",
    ingredients: [
      "250 gram tepung terigu",
      "200 gram gula pasir",
      "3 butir telur",
      "1 sdt SP/ovalet",
      "200 ml minuman soda tawar",
      "1 sdt vanili",
      "Pewarna makanan (opsional)",
    ],
    steps: [
      "Kocok telur, gula, dan SP hingga mengembang dan putih.",
      "Masukkan vanili dan tepung terigu, aduk rata.",
      "Tuang soda sedikit demi sedikit sambil diaduk perlahan.",
      "Bagi adonan dan beri warna sesuai selera.",
      "Tuang ke cetakan, kukus selama ±15 menit hingga matang.",
      "Angkat dan sajikan bolu kukus.",
    ],
  ),

  Recipe(
    id: 99,
    title: "Pastel Goreng",
    description:
        "Pastel goreng adalah camilan renyah berisi sayuran dan telur dengan kulit garing.",
    imageUrl: "images/pastel.jpg",
    ingredients: [
      "Kulit pastel siap pakai",
      "2 buah kentang, potong dadu kecil",
      "1 buah wortel, potong dadu kecil",
      "2 butir telur rebus, potong",
      "3 siung bawang putih, cincang",
      "1/2 sdt garam",
      "1/4 sdt merica",
      "Minyak goreng secukupnya",
    ],
    steps: [
      "Tumis bawang putih hingga harum.",
      "Masukkan kentang dan wortel, masak hingga empuk.",
      "Bumbui garam dan merica, angkat.",
      "Isi kulit pastel dengan tumisan sayur dan telur.",
      "Tutup dan rekatkan pinggirnya.",
      "Goreng hingga pastel kuning keemasan.",
      "Angkat dan sajikan pastel goreng hangat.",
    ],
  ),

  Recipe(
    id: 100,
    title: "Pisang Nugget",
    description:
        "Pisang nugget adalah olahan pisang modern yang digoreng dengan balutan tepung dan disajikan dengan aneka topping.",
    imageUrl: "images/pisangnugget.jpg",
    ingredients: [
      "6 buah pisang kepok matang",
      "100 gram tepung terigu",
      "2 sdm gula pasir",
      "1/4 sdt garam",
      "Tepung panir secukupnya",
      "Minyak goreng",
      "Cokelat meses / keju / susu kental manis (topping)",
    ],
    steps: [
      "Haluskan pisang, campur dengan tepung, gula, dan garam.",
      "Tuang adonan ke loyang, kukus hingga matang.",
      "Potong-potong adonan, balur dengan tepung panir.",
      "Goreng hingga nugget pisang kecokelatan.",
      "Tambahkan topping sesuai selera.",
      "Sajikan pisang nugget hangat.",
    ],
  ),
];
