import 'resep.dart';

final List<Recipe> sliderResep = [
  Recipe(
    id: 1,
    title: "Nasi Goreng Spesial",
    description:
        "Nasi goreng khas Indonesia dengan cita rasa gurih, dilengkapi telur, ayam suwir, dan sayuran segar. Cocok untuk sarapan maupun makan malam.",
    imageUrl: "images/nasgor2.jpg",
    ingredients: [
      "2 piring nasi putih (sebaiknya nasi dingin)",
      "2 butir telur ayam",
      "100 gram ayam dada, rebus lalu suwir",
      "3 siung bawang merah, iris halus",
      "2 siung bawang putih, cincang",
      "2 sdm kecap manis",
      "1 sdm kecap asin",
      "1/2 sdt merica bubuk",
      "1/2 sdt garam",
      "1/2 sdt kaldu bubuk",
      "1 batang daun bawang, iris",
      "1 sdm minyak goreng",
      "Acar & kerupuk (pelengkap)",
    ],
    steps: [
      "Panaskan minyak goreng di wajan dengan api sedang.",
      "Tumis bawang merah dan bawang putih hingga harum dan sedikit kecoklatan.",
      "Masukkan telur, orak-arik hingga setengah matang.",
      "Masukkan ayam suwir, aduk hingga tercampur rata.",
      "Masukkan nasi putih, aduk dan tekan agar nasi terurai.",
      "Tambahkan kecap manis, kecap asin, garam, merica, dan kaldu bubuk.",
      "Aduk rata hingga nasi berubah warna dan bumbu meresap.",
      "Masukkan daun bawang, aduk sebentar lalu koreksi rasa.",
      "Angkat dan sajikan nasi goreng selagi hangat.",
      "Sajikan dengan acar, kerupuk, dan telur mata sapi jika suka.",
    ],
  ),

  Recipe(
    id: 2,
    title: "Mie Goreng",
    description:
        "Mie goreng sederhana dengan cita rasa gurih dan lezat, dipadukan dengan sayuran segar dan bumbu khas rumahan. Cocok untuk menu cepat dan praktis.",
    imageUrl: "images/migor.jpg",
    ingredients: [
      "1 bungkus mie telur atau mie instan tanpa bumbu",
      "1 butir telur ayam",
      "2 siung bawang putih, cincang halus",
      "1/2 buah bawang bombay, iris tipis",
      "1 batang daun bawang, iris",
      "1 genggam sawi hijau atau kol, iris",
      "2 sdm kecap manis",
      "1 sdm kecap asin",
      "1/2 sdt merica bubuk",
      "1/2 sdt garam",
      "1/2 sdt kaldu bubuk (opsional)",
      "1 sdm minyak goreng",
      "Acar dan kerupuk (pelengkap)",
    ],
    steps: [
      "Rebus mie hingga setengah matang, tiriskan dan sisihkan.",
      "Panaskan minyak goreng di wajan dengan api sedang.",
      "Tumis bawang putih dan bawang bombay hingga harum.",
      "Masukkan telur, orak-arik hingga matang.",
      "Masukkan sayuran, tumis sebentar hingga layu.",
      "Masukkan mie rebus ke dalam wajan, aduk rata.",
      "Tambahkan kecap manis, kecap asin, garam, merica, dan kaldu bubuk.",
      "Aduk terus hingga bumbu merata dan mie matang sempurna.",
      "Masukkan daun bawang, aduk sebentar lalu angkat.",
      "Sajikan mie goreng selagi hangat dengan acar dan kerupuk.",
    ],
  ),

  Recipe(
    id: 3,
    title: "Ayam Geprek",
    description:
        "Ayam goreng crispy yang digeprek bersama sambal bawang pedas, menghasilkan perpaduan rasa gurih, renyah, dan pedas yang menggugah selera. Cocok untuk pencinta makanan pedas.",
    imageUrl: "images/ayprek.jpg",
    ingredients: [
      "2 potong ayam goreng crispy",
      "10 buah cabai rawit merah (sesuai selera)",
      "4 siung bawang putih",
      "1/2 sdt garam",
      "1/4 sdt gula pasir",
      "1/4 sdt kaldu bubuk (opsional)",
      "3 sdm minyak goreng panas",
      "Nasi putih hangat (pelengkap)",
      "Lalapan segar (opsional)",
    ],
    steps: [
      "Goreng ayam crispy hingga matang dan berwarna keemasan, lalu tiriskan.",
      "Siapkan cobek, masukkan cabai rawit, bawang putih, garam, gula, dan kaldu bubuk.",
      "Ulek bahan sambal hingga halus atau sesuai tekstur yang diinginkan.",
      "Siram sambal dengan minyak goreng panas agar aroma lebih harum.",
      "Letakkan ayam goreng di atas sambal, lalu geprek hingga ayam sedikit hancur dan sambal meresap.",
      "Sajikan ayam geprek selagi hangat bersama nasi putih dan lalapan.",
    ],
  ),
];